# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_extensions', '0005_auto_20170210_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorporateImage',
        ),
    ]
