# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_extensions', '0008_auto_20170307_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityLocaleNameEN',
            new_name='CityGeoNameEN',
        ),
        migrations.RenameModel(
            old_name='CityLocaleNameES',
            new_name='CityGeoNameES',
        ),
        migrations.RenameModel(
            old_name='ContinentLocaleNameEN',
            new_name='ContinentGeoNameEN',
        ),
        migrations.RenameModel(
            old_name='ContinentLocaleNameES',
            new_name='ContinentGeoNameES',
        ),
        migrations.RenameModel(
            old_name='CountryLocaleNameEN',
            new_name='CountryGeoNameEN',
        ),
        migrations.RenameModel(
            old_name='CountryLocaleNameES',
            new_name='CountryGeoNameES',
        ),
        migrations.RenameModel(
            old_name='ProvinceLocaleNameEN',
            new_name='ProvinceGeoNameEN',
        ),
        migrations.RenameModel(
            old_name='ProvinceLocaleNameES',
            new_name='ProvinceGeoNameES',
        ),
        migrations.RenameModel(
            old_name='RegionLocaleNameEN',
            new_name='RegionGeoNameEN',
        ),
        migrations.RenameModel(
            old_name='RegionLocaleNameES',
            new_name='RegionGeoNameES',
        ),
    ]
