# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_extensions', '0009_auto_20170320_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateimage',
            name='name_file_logo',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Name file company logo'),
        ),
        migrations.AddField(
            model_name='corporateimage',
            name='name_file_seal',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Name file company seal'),
        ),
        migrations.AddField(
            model_name='corporateimage',
            name='name_file_sign',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Name file digital sign'),
        ),
    ]
