# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_extensions', '0011_auto_20170428_1007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorporateImage',
        ),
    ]
